### ISSUE TITLE
NPE si authentification par mail après création de compte par OAuth2

### ISSUE THREAD

**Issue by jljouannic** [breizhcamp/callForPaper#32]
Pour reproduire :

* BDD vierge,
* première connexion avec authentification Google.
* déconnexion,
* tentative d'autentification avec saisie email plus mot de passe (n'importe quoi…).
==> NPE
```
java.lang.NullPointerException: null
	at org.mindrot.jbcrypt.BCrypt.hashpw(BCrypt.java:663) ~[jbcrypt-0.3m.jar:na]
	at org.mindrot.jbcrypt.BCrypt.checkpw(BCrypt.java:763) ~[jbcrypt-0.3m.jar:na]
	at fr.sii.service.auth.PasswordService.checkPassword(PasswordService.java:25) ~[classes/:na]
	at fr.sii.controller.oauth.AuthController.login(AuthController.java:72) ~[classes/:na]
```

C'est clairement un cas limite, puisqu'on n'est pas censé s'authentifier de la sorte après avoir utilisé l'autent Google pour créer son compte utilisateur. Malgré tout, cela mériterait un message d'erreur explicite envoyé au client.

**Comment by jljouannic** [comment]
À voir en même temps que #39 ?

**Comment by nbulteau** [comment]
C'est lié au fait que lorsqu'un utilisateur a un googleId ou un githubId il n'est pas censé avoir de password. Je corrige et j'envoie un message plus explicite.
