### ISSUE TITLE
page d'accueil qui boucle

### ISSUE THREAD

**Issue by ndeloof** [breizhcamp/callForPaper#50]
en cas de problème d'authent (genre, changement des clés OAuth ...)
la page de login boucle :

```
Request URL:https://cfp.breizhcamp.org/api/restricted/user
Request Method:GET
Status Code:400 Bad Request
Remote Address:104.155.87.2:443

Response Headers
Access-Control-Allow-Headers:Authorization
Access-Control-Allow-Origin:*
Connection:close
Content-Type:application/json;charset=UTF-8
Date:Thu, 10 Dec 2015 18:27:53 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
```

**Comment by ydubreuil** [comment]
Ca boucle car le token de signature n'est pas invalidé dans le navigateur. Exception sur le serveur:
```
com.nimbusds.jose.JOSEException: Signature verification failed
	at fr.sii.service.auth.AuthUtils.decodeToken(AuthUtils.java:75)
	at fr.sii.service.auth.AuthUtils.getTokenBody(AuthUtils.java:52)
	at fr.sii.controller.common.user.AdminUserController.getCurrentUser(AdminUserController.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by ndeloof** [comment]
un passage par https://cfp.breizhcamp.org/#/logout règle le problème (pour moi en tout cas)

**Comment by ydubreuil** [comment]
Il faut invalider le token CSRF pour que ça remarche. Au lieu de boucler, il faut faire la même chose que Logout.

**Comment by ydubreuil** [comment]
Il semble que le token soit dans le local storage, ce qui explique d'une fermeture d'onglet ne suffise pas à résoudre le pb :(
