### ISSUE TITLE
Création d'un compte local renvoie sur une page d'erreur

### ISSUE THREAD

**Issue by ydubreuil** [breizhcamp/callForPaper#51]
Lorsqu'on se crée un compte local, on est redirigé vers une page d'erreur après la création du compte car le compte de l'utilisateur n'a pas été vérifié.

Le mail part bien quand même et on peut activer son compte en cliquant sur le lien du mail.

Exception dans le log:
```
2015-12-11 07:25:52.854 DEBUG 6 --- [nio-8443-exec-2] fr.sii.service.email.EmailingService     : Sent e-mail to User 'XXXXXXXXXX@XXXXX'
2015-12-11 07:25:52.943 DEBUG 6 --- [nio-8443-exec-9] f.s.c.e.GlobalControllerExceptionHandler : fr.sii.domain.exception.NotVerifiedException: User must be verified

fr.sii.domain.exception.NotVerifiedException: User must be verified
	at fr.sii.controller.restricted.RestrictedController.retrieveUserId(RestrictedController.java:24) ~[call-for-paper.jar!/:1.0-SNAPSHOT]
	at fr.sii.controller.restricted.user.UserController.getUserProfil(UserController.java:42) ~[call-for-paper.jar!/:1.0-SNAPSHOT]

```

**Comment by nbulteau** [comment]
Il semble qu'on ne soit pas (plus ?) redirigé vers http://127.0.0.1:3000/#/login ... mais http://127.0.0.1:3000/#/dashboard

**Comment by ndeloof** [comment]
a vue de nez, il faut configurer `$authProvider.signupRedirect` pour renvoyer vers une page expliquant l'attente de confirmation d'email. 
Ce serait encore mieux que la 403 sache identifier un sign-up incomplet et indiquer à l'utilisateur de vérifier ses mails

**Comment by jljouannic** [comment]
> … pour renvoyer vers une page expliquant l'attente de confirmation d'email.

Cette page existe déjà (`verify.{js,html}` de mémoire). Ça fonctionnait comme prévu il y a une dizaine de jours.
